/*
 * Driftwood Isles — pixel-art icon set.
 * Plain browser ES module, no imports. All DOM/canvas access is lazy inside
 * functions so the module can be parsed/imported under plain node.
 *
 * Icons are 16x16 pixel grids (strings of palette characters) rendered to a
 * canvas with integer fillRect calls only, then cached as PNG data URLs.
 * Style: 1px dark outline, warm saturated fills, single light highlight.
 */

const OUTLINE = '#2a2018';

// Shared palette. Individual icons may override characters via their `p` map.
const BASE_PALETTE = {
  o: OUTLINE,      // dark outline
  O: '#4a3a28',    // soft inner shade
  w: '#f2e6c8',    // cream / paper
  W: '#ffffff',    // pure white highlight
  r: '#c0342b',    // red
  R: '#e05a4e',    // light red
  g: '#d9a13c',    // gold
  G: '#f0c95c',    // light gold
  y: '#ffe9a0',    // pale yellow highlight
  n: '#8a5a2b',    // brown
  N: '#b07a40',    // light brown
  d: '#5a3a1c',    // dark brown
  e: '#3e9444',    // green
  E: '#7cc860',    // light green
  b: '#2f6fc4',    // blue
  B: '#66aae0',    // light blue
  L: '#a8d4f0',    // pale blue
  k: '#3b3a44',    // dark iron
  s: '#98a0ac',    // silver
  S: '#cfd6dd',    // light silver
  t: '#2fa89e',    // teal
  T: '#6fd8cc',    // light teal
  p: '#7d3fae',    // purple
  P: '#a86fd4',    // light purple
  i: '#e87a9e',    // pink
  I: '#f5aac4',    // light pink
  a: '#e6cf96',    // sand
  A: '#f2e2b0',    // light sand
  v: '#1d3f8a',    // navy (fish silhouette)
};

// Each icon: { g: [16 row strings], p?: palette overrides }
const GRIDS = {

  // ------------------------------------------------------------- UI / tabs
  backpack: { g: [
    '................',
    '....oooooooo....',
    '...odyddddddo...',
    '..odddddddddoo..',
    '..oddddddddddo..',
    '..oooooooooooo..',
    '.oNyNNNNNNNNNNo.',
    '.oNnnnnnnnnnnNo.',
    '.oNnnooooonnnNo.',
    '.oNnnoGGgonnnNo.',
    '.oNnnoggggnnnNo.',
    '.oNnnooooonnnNo.',
    '.oNnnnnnnnnnnNo.',
    '..oNNnnnnnnNNo..',
    '...oooooooooo...',
    '................',
  ] },
  dex: { g: [
    '................',
    '................',
    '.ooo........ooo.',
    '.owwoo....oowwo.',
    '.owwwwoooowwwwo.',
    '.owswwwoowwwswo.',
    '.owwwwwoowwwwwo.',
    '.owswswoowswswo.',
    '.owwwwwoowwwwwo.',
    '.owswwwoowwwswo.',
    '.owwwwwoowwwwwo.',
    '.oowwwwoowwwwoo.',
    '..ooooo..ooooo..',
    '................',
    '................',
    '................',
  ] },
  skill: { g: [
    '................',
    '................',
    '................',
    '....ooooo.......',
    '..oovvvvvoo.oo..',
    '.ovvvvvvvvvoovo.',
    'ovvovvvvvvvvvvo.',
    'ovvvvvvvvvvvvvo.',
    '.ovvvvvvvvvoovo.',
    '..oovvvvvoo.oo..',
    '....ooooo.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },
  trophy: { g: [
    '................',
    '.oooooooooooooo.',
    '.ogGGGGGGGGGggo.',
    '.oogGGGGGGGgoo..',
    'oo.ogyGGGGggo.oo',
    'ogo.ogGGGGgo.ogo',
    'ogo.ogGGGGgo.ogo',
    'ooo.ogGGGggo.ooo',
    '.....ogGggo.....',
    '......oggo......',
    '......oggo......',
    '.....ooggoo.....',
    '....oggggggo....',
    '...oggggggggo...',
    '...oooooooooo...',
    '................',
  ] },
  rod: { g: [
    '..............o.',
    '.............oo.',
    '...........ooNo.',
    '..........oNNoo.',
    '.........oNNo.o.',
    '........oNNo..o.',
    '.......onNo...o.',
    '......onno....o.',
    '.....onno.....o.',
    '....onno......o.',
    '...odno.......o.',
    '..odno......ooo.',
    '.oddo......orRo.',
    '.odo.......oRWo.',
    '.oo.........oo..',
    '................',
  ] },
  potion: { g: [
    '................',
    '......oooo......',
    '......osso......',
    '......owwo......',
    '......owwo......',
    '.....oowwoo.....',
    '....owwwwwwo....',
    '...owwwwwwwwo...',
    '..owwoppppwwwo..',
    '..owpPPpppppwo..',
    '..opPPPpppppo...',
    '..opPPpppppppo..',
    '..oppppppppppo..',
    '...oppppppppo...',
    '....oooooooo....',
    '................',
  ] },
  map: { g: [
    '................',
    '................',
    '..oo...ooo..oo..',
    '.oawooowawooawo.',
    '.oaawwawwawwaao.',
    '.oaawaaawaawaao.',
    '.oawwarraawwaao.',
    '.oawaarraaawaao.',
    '.oawaaaaaaawaao.',
    '.oawaaeeaawwaao.',
    '.oawaaeeaaawaao.',
    '.oaawaaaawaaawo.',
    '.oaawwaawwaawao.',
    '.oawooowawooawo.',
    '..oo...ooo..oo..',
    '................',
  ] },
  island: { g: [
    '................',
    '...oo.....oo....',
    '..oEEoo.ooEEo...',
    '.oEEEEEoEEEEEo..',
    '.oEeoeEEEeoeEEo.',
    '..ooooeEeooooo..',
    '......oeeo......',
    '......oeeo......',
    '.....oeeo.......',
    '.....oeeo.......',
    '.....oneo.......',
    '....oAAnAoo.....',
    '..ooAAAAAAAoo...',
    '.oaAAAAAAAAAao..',
    '.ooaaaaaaaaaoo..',
    '................',
  ] },
  settings: { g: [
    '................',
    '......oooo......',
    '..oo.osSSso.oo..',
    '.osso.ossoossso.',
    '.osssoossoosss..',
    '..ossssssssss o.',
    '..osssoooossso..',
    '.ossso....오sso.',
    '.oSsso....ossSo.',
    '..osssoooossso..',
    '..osssssssssso..',
    '.osssoossoossso.',
    '.osso.ossо.osso.',
    '..oo.osSSso.oo..',
    '......oooo......',
    '................',
  ] },
  lobby: { g: [
    '................',
    '................',
    '...ooo....ooo...',
    '..oNNNo..odddo..',
    '.oNyNNNoodydddo.',
    '.oNNNNNoodddddo.',
    '.oNNNNNoodddddo.',
    '..oNNNo..odddo..',
    '...ooo....ooo...',
    '..ooooo..ooooo..',
    '.orrrrroobbbbbo.',
    '.orRrrroobBbbbo.',
    '.orrrrroobbbbbo.',
    '.orrrrroobbbbbo.',
    '.ooooooooooooo..',
    '................',
  ] },
  close: { g: [
    '................',
    '................',
    '..oo........oo..',
    '.orro......orro.',
    '.oRrro....orrro.',
    '..orrro..orrro..',
    '...orrroorrro...',
    '....orrrrrro....',
    '.....orrrro.....',
    '....orrrrrro....',
    '...orrroorrro...',
    '..orrro..orrro..',
    '.orrro....orrro.',
    '.orro......orro.',
    '..oo........oo..',
    '................',
  ] },

  // --------------------------------------------------------- currency / HUD
  coin: { g: [
    '................',
    '.....oooooo.....',
    '...oogGGGggoo...',
    '..ogGyGGGGggo...',
    '..ogyGGGGGGggo..',
    '.ogGGooooogggo..',
    '.ogGGo...oggggo.',
    '.ogGGo...oggggo.',
    '.ogGGo...oggggo.',
    '.ogGGo...oggggo.',
    '.oggGooooogggo..',
    '..oggggggggggo..',
    '..ogggggggggo...',
    '...oogggggoo....',
    '.....oooooo.....',
    '................',
  ] },
  sun: { g: [
    '................',
    '.......oo.......',
    '.o.....oo.....o.',
    '..o..oooooo..o..',
    '...ooGGGGGGoo...',
    '...oGyyGGGGGo...',
    '..ooGyGGGGGGoo..',
    '.oooGGGGGGGGooo.',
    '.oooGGGGGGGGooo.',
    '..ooGGGGGGGGoo..',
    '...oGGGGGGGGo...',
    '...ooGGGGGGoo...',
    '..o..oooooo..o..',
    '.o.....oo.....o.',
    '.......oo.......',
    '................',
  ], p: { G: '#f4b93c' } },
  moon: { g: [
    '................',
    '.....ooooo......',
    '....oyyyyoo.....',
    '...oyyyoooo.....',
    '..oyyyo.........',
    '..oyyo..........',
    '.oyyyo.....o....',
    '.oyyyo....oyo...',
    '.oyyyo.....o....',
    '.oyyyo..........',
    '..oyyo..........',
    '..oyyyo.........',
    '...oyyyoooo.....',
    '....oyyyyoo.....',
    '.....ooooo......',
    '................',
  ], p: { y: '#f2d876' } },
  dusk: { g: [
    '................',
    '................',
    '................',
    '.......oo.......',
    '..o....oo....o..',
    '...o.oooooo.o...',
    '....ooGGGGoo....',
    '...ooGyGGGGoo...',
    '...oGyGGGGGGo...',
    '..ooGGGGGGGGoo..',
    'oooooooooooooooo',
    '.obbBbbbbbBbbbo.',
    '.obbbbBbbbbbbo..',
    '..oooooooooooo..',
    '................',
    '................',
  ], p: { G: '#f09c3a' } },
  bait: { g: [
    '................',
    '................',
    '................',
    '....ooooo.......',
    '...oiIIiioo.....',
    '..oiIooooiio....',
    '..oiio...oiio...',
    '..oiio....oiio..',
    '...oo......oiio.',
    '.....oo....oiio.',
    '....oiio..oiio..',
    '...oiiiooiiio...',
    '....oiiiiiio....',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  level: { g: [
    '................',
    '.......oo.......',
    '......oGGo......',
    '.....oGyGGo.....',
    '....oGyGGGGo....',
    '...oGGGGGGGGo...',
    '..oGGGGGGGGGGo..',
    '.oooooGGGGooooo.',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oooooo.....',
    '................',
    '................',
  ], p: { G: '#5cb85c', y: '#a8e6a0' } },
  xp: { g: [
    '................',
    '................',
    '.......oo.......',
    '......oGGo......',
    '......oGGo......',
    '.....oGyGGo.....',
    '..oooGyGGGooo...',
    '.oGGGGyGGGGGGo..',
    '..oooGGGGGooo...',
    '.....oGGGGo.....',
    '......oGGo......',
    '......oGGo......',
    '.......oo.......',
    '................',
    '................',
    '................',
  ] },

  // ---------------------------------------------------------------- fishing
  bobber: { g: [
    '................',
    '.......o........',
    '.......o........',
    '......ooo.......',
    '.....ooooo......',
    '....orrRrro.....',
    '...orrrRrrro....',
    '...orrrrrrro....',
    '...ooooooooo....',
    '...owwwwwwwo....',
    '...oWwwwwwwo....',
    '....owwwwwo.....',
    '.....ooooo......',
    '......ooo.......',
    '................',
    '................',
  ] },
  hook: { g: [
    '................',
    '......oo........',
    '.....oSso.......',
    '.....osso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '..oo..oso.......',
    '.oSso.oso.......',
    '.osso.osso......',
    '..ossoosso......',
    '...ossssoo......',
    '....oooo........',
    '................',
  ] },
  reel: { g: [
    '................',
    '.....ooooo......',
    '...oodddddoo....',
    '..odddooodddo...',
    '.oddo.....oddo..',
    '.odo..ooo..odo..',
    'oddo.osSso.oddoo',
    'odo..ososo..odoo',
    'oddo.ossso.oddo.',
    '.odo..ooo..odoo.',
    '.oddo.....oddo..',
    '..odddooodddo...',
    '...oodddddoo..o.',
    '.....ooooo...o..',
    '............o...',
    '................',
  ], p: { d: '#7a3a20' } },
  gadget: { g: [
    '................',
    '................',
    '..oo......oo....',
    '.osSo....osSoo..',
    '.osso....osssso.',
    '.ossoo..oossso..',
    '.osssoooosssо...',
    '..ossssssssо....',
    '...oossssoo.....',
    '.....osssso.....',
    '......ossso.....',
    '.......ossso....',
    '........ossso...',
    '.........osso...',
    '..........oo....',
    '................',
  ] },
  sonar: { g: [
    '................',
    '................',
    '..ooo...........',
    '.oTTto...ooo....',
    '.oTto...ottto...',
    '.otto..otto.....',
    '.otto..otto..oo.',
    '.otto..otto.oto.',
    '.otto..otto.oto.',
    '.otto..otto..oo.',
    '.otto..otto.....',
    '.oTto...ottto...',
    '.oTTto...ooo....',
    '..ooo...........',
    '................',
    '................',
  ] },
  scope: { g: [
    '................',
    '................',
    '.........oooo...',
    '........okkkko..',
    '.......okLLskо..',
    '......okLskkko..',
    '.....osksskko...',
    '....ossso.oo....',
    '...osssо........',
    '...ossso........',
    '..onnsо.........',
    '.onnnо..........',
    '.onno...........',
    '..oo............',
    '................',
    '................',
  ] },

  magnet: { g: [
    '................',
    '................',
    '..oooo....oooo..',
    '.orrrro..orrrro.',
    '.oRrrro..orrRro.',
    '.orrrro..orrrro.',
    '.oooooo..oooooo.',
    '.oSSSSo..oSSSSo.',
    '.osssso..osssso.',
    '.ossssoooosssso.',
    '.osssssssssssso.',
    '..ossssssssssо..',
    '...osssssssso...',
    '....oooooooo....',
    '................',
    '................',
  ] },
  autoreel: { g: [
    '.oooo...........',
    '..yyo...........',
    '..oy............',
    '.oyyo..oooo.....',
    '.oooo...yyo.....',
    '........oy......',
    '.......oyyo.....',
    '.......oooo.....',
    '....ooooo.......',
    '..oodddddoo.....',
    '.oddooooоddo....',
    '.odo.osso.odo...',
    '.odo.osso.odo...',
    '.oddoooooddo....',
    '..oodddddoo.....',
    '....ooooo.......',
  ], p: { d: '#7a3a20', y: '#f2d876' } },
  tension: { g: [
    '................',
    '......oooo......',
    '.....orrrro.....',
    '.....orRrro.....',
    '.....orRrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '......orro......',
    '......orro......',
    '.......oo.......',
    '......oooo......',
    '.....orrrro.....',
    '.....orrrro.....',
    '......oooo......',
    '................',
  ] },
  fish: { g: [
    '................',
    '................',
    '................',
    '.....ooooo......',
    '...oobBBbboo.oo.',
    '..obBBbbbbbooBo.',
    '.obBoWbbbbbboBBo',
    '.oboooObbbbbbBo.',
    '.obbbbbbbbbooBo.',
    '..obbbbbbbo.oBo.',
    '...oobbboo...oo.',
    '.....ooooo......',
    '................',
    '................',
    '................',
    '................',
  ] },
  fish_rare: { g: [
    '.......o........',
    '......oyo..o....',
    '.......o........',
    '.....ooooo......',
    '...ooGGGGgoo.oo.',
    '..oGGGggggggooGo',
    '.oGGoWgggggggGGo',
    '.ogoooOgggggggо.',
    '.oggggggggggooGo',
    '..ogggggggо..oGo',
    '...oogggoo....oo',
    '.....ooooo......',
    '..o.............',
    '.oyo............',
    '..o.............',
    '................',
  ] },
  whale: { g: [
    '................',
    '....o.o.........',
    '....ooo.........',
    '.....o..........',
    '....ooooooo.....',
    '..oobbbbbbboo...',
    '.obbbbbbbbbbboo.',
    'obbWobbbbbbbbobo',
    'obbоobbbbbbbobbo',
    'obbbbbbbbbboobbo',
    '.oLLLbbbbbbbobo.',
    '..oLLLLbbbboo.o.',
    '...ooooooooo....',
    '................',
    '................',
    '................',
  ], p: { b: '#3a6ea8', L: '#bcd8ec' } },
  junk: { g: [
    '................',
    '................',
    '....oooo........',
    '...odddNo.......',
    '...oddddo.......',
    '...odоddo.......',
    '...odddNo.......',
    '...oddddo.......',
    '...oddddo.......',
    '...oddddoooo....',
    '...odddddNNNoo..',
    '...oddddddddNNo.',
    '..oododdddddddo.',
    '..oo.ooooooooo..',
    '................',
    '................',
  ], p: { d: '#6a4a2a', N: '#8a6a3a' } },
  treasure: { g: [
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..oNyNNNNNNNNo..',
    '..oNNNNNNNNNNo..',
    '.oooooooooooooo.',
    '.onnnnoggonnnno.',
    '.onnnnoGgonnnno.',
    '.onnnnoooonnnno.',
    '.onnnnnnnnnnnno.',
    '.onnnnnnnnnnnno.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ] },
  record: { g: [
    '................',
    '...ooooooooo....',
    '...obbo.orro....',
    '...obbo.orro....',
    '...obbo.orro....',
    '...obboorro.....',
    '....obborо......',
    '....ooooo.......',
    '...ooGGGoo......',
    '..oGGyGGGGo.....',
    '..oGyGooGGo.....',
    '..oGGoGGoGo.....',
    '..oGGooоGGо.....',
    '...oGGGGGо......',
    '....ooooo.......',
    '................',
  ] },

  // ---------------------------------------------------------- world/actions
  bank: { g: [
    '................',
    '................',
    '...oooooooooo...',
    '..odyddddddddo..',
    '..oddddddddddo..',
    '..ogGgggggggGo..',
    '.oooooooooooooo.',
    '.odddoggggodddo.',
    '.odddogGggodddo.',
    '.odddoggggodddo.',
    '.odddooooоdddo..',
    '.odddddddddddо..',
    '.ogGgggggggggGo.',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  shop: { g: [
    '.oooooooooooooo.',
    '.owrwrwrwrwrwwo.',
    '.owrwrwrwrwrwwo.',
    '.oooooooooooooo.',
    '....o......o....',
    '....o......o....',
    '..oooooooooooo..',
    '.oNNNNNNNNNNNNo.',
    '.oNyNNNNNNNNNNo.',
    '.oNodoNNNNodoNo.',
    '.oNodoNNNNodoNo.',
    '.oNNNNNNNNNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  ferry: { g: [
    '................',
    '................',
    '.......oo.......',
    '......owwo......',
    '......owwoo.....',
    '......owwwwo....',
    '......owwwwwo...',
    '......oooooo....',
    '..o....odd..o...',
    '..oo...odd.oo...',
    '.oonoooooooноo..',
    '.onnnnnnnnnnno..',
    '..onnnnnnnnnо...',
    '...ooooooooo....',
    '....bbBbbBbb....',
    '................',
  ] },
  portal: { g: [
    '................',
    '.....oooooo.....',
    '...ootTTTtoo....',
    '..otTToootTto...',
    '..oTtо....otto..',
    '.otTo......otto.',
    '.oTto......otto.',
    '.oTto......otto.',
    '.otto......otto.',
    '.otto......otTo.',
    '..otto....оtto..',
    '..ottToootTto...',
    '...ootTTTtoo....',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  talk: { g: [
    '................',
    '................',
    '..oooooooooooo..',
    '.owwwwwwwwwwwwo.',
    '.oWwwwwwwwwwwwo.',
    '.owwooWwooWwowo.',
    '.owwoowwoowwowo.',
    '.owwwwwwwwwwwwo.',
    '.owwwwwwwwwwwwo.',
    '..oooowwwooooo..',
    '.....owwo.......',
    '....owwo........',
    '...owwo.........',
    '...ooo..........',
    '................',
    '................',
  ] },
  examine: { g: [
    '................',
    '....ooooo.......',
    '...oosssoo......',
    '..oso...oso.....',
    '.oso.....oso....',
    '.oso..W..oso....',
    '.oso.....oso....',
    '.oso.....oso....',
    '..oso...oso.....',
    '...oosssoo......',
    '....ooooooo.....',
    '.......onnno....',
    '........onnno...',
    '.........onnno..',
    '..........ooo...',
    '................',
  ], p: { s: '#7ab8d8', W: '#e8f4fa' } },
  walk: { g: [
    '................',
    '.........ooo....',
    '........oNNNo...',
    '........oNNNo...',
    '........oNNNо...',
    '.........ooo....',
    '........oNNo....',
    '.........oo.....',
    '..ooo...........',
    '.oNNNo..........',
    '.oNNNo..........',
    '.oNNNo..........',
    '..ooo...........',
    '.oNNo...........',
    '..oo............',
    '................',
  ] },
  wave: { g: [
    '................',
    '.....o.o.o......',
    '....oNoNoNoo....',
    '....oNNNNNNNoo..',
    '.o..oNNNNNNNNNo.',
    '.oNooNNNNNNNNNо.',
    '..oNoNNNNNNNNNo.',
    '..oNNNNNNNNNNNo.',
    '...oNNyNNNNNNо..',
    '...oNNNNNNNNNо..',
    '....oNNNNNNNо...',
    '....oNNNNNNNo...',
    '.....ooooooo....',
    '................',
    '................',
    '................',
  ] },
  key: { g: [
    '................',
    '................',
    '...oooo.........',
    '..ogGGgo........',
    '.ogGо.ogo.......',
    '.oGо...ogo......',
    '.ogо..ogо.......',
    '..ogggо.ogo.....',
    '...oo....ogo....',
    '..........ogo...',
    '...........ogoo.',
    '..........ogGgo.',
    '.........ogо.go.',
    '..........оggо..',
    '...........oo...',
    '................',
  ] },
  sign: { g: [
    '................',
    '................',
    '..oooooooooooo..',
    '.oNyNNNNNNNNNNo.',
    '.oNNNddNddNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '.oNNdNddNdNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '..oooooooooooo..',
    '......oddo......',
    '......oddo......',
    '......oddo......',
    '......oddo......',
    '.....ooddoo.....',
    '................',
    '................',
  ] },
