/*
 * Driftwood Isles o pixel-art icon set.
 * Plain browser ES module, no imports. All DOM/canvas access is lazy inside
 * functions so the module can be parsed/imported under plain node.
 *
 * Icons are 16x16 pixel grids (strings of palette characters) rendered to a
 * canvas with integer fillRect calls only, then cached as PNG data URLs.
 * Style: 1px dark outline, warm saturated fills, single light highlight.
 */

const OUTLINE = '#2a2018';

// Shared palette. Individual icons may override characters via their `p` map.
const BASE_PALETTE = {
  o: OUTLINE,      // dark outline
  O: '#4a3a28',    // soft inner shade
  w: '#f2e6c8',    // cream / paper
  W: '#ffffff',    // pure white highlight
  r: '#c0342b',    // red
  R: '#e05a4e',    // light red
  g: '#d9a13c',    // gold
  G: '#f0c95c',    // light gold
  y: '#ffe9a0',    // pale yellow highlight
  n: '#8a5a2b',    // brown
  N: '#b07a40',    // light brown
  d: '#5a3a1c',    // dark brown
  e: '#3e9444',    // green
  E: '#7cc860',    // light green
  b: '#2f6fc4',    // blue
  B: '#66aae0',    // light blue
  L: '#a8d4f0',    // pale blue
  k: '#3b3a44',    // dark iron
  s: '#98a0ac',    // silver
  S: '#cfd6dd',    // light silver
  t: '#2fa89e',    // teal
  T: '#6fd8cc',    // light teal
  p: '#7d3fae',    // purple
  P: '#a86fd4',    // light purple
  i: '#e87a9e',    // pink
  I: '#f5aac4',    // light pink
  a: '#e6cf96',    // sand
  A: '#f2e2b0',    // light sand
  v: '#1d3f8a',    // navy (fish silhouette)
};

// Each icon: { g: [16 row strings], p?: palette overrides }
const GRIDS = {

  // ------------------------------------------------------------- UI / tabs
  backpack: { g: [
    '................',
    '....oooooooo....',
    '...odyddddddo...',
    '..odddddddddoo..',
    '..oddddddddddo..',
    '..oooooooooooo..',
    '.oNyNNNNNNNNNNo.',
    '.oNnnnnnnnnnnNo.',
    '.oNnnooooonnnNo.',
    '.oNnnoGGgonnnNo.',
    '.oNnnoggggnnnNo.',
    '.oNnnooooonnnNo.',
    '.oNnnnnnnnnnnNo.',
    '..oNNnnnnnnNNo..',
    '...oooooooooo...',
    '................',
  ] },
  dex: { g: [
    '................',
    '................',
    '.ooo........ooo.',
    '.owwoo....oowwo.',
    '.owwwwoooowwwwo.',
    '.owswwwoowwwswo.',
    '.owwwwwoowwwwwo.',
    '.owswswoowswswo.',
    '.owwwwwoowwwwwo.',
    '.owswwwoowwwswo.',
    '.owwwwwoowwwwwo.',
    '.oowwwwoowwwwoo.',
    '..ooooo..ooooo..',
    '................',
    '................',
    '................',
  ] },
  skill: { g: [
    '................',
    '................',
    '................',
    '....ooooo.......',
    '..oovvvvvoo.oo..',
    '.ovvvvvvvvvoovo.',
    'ovvovvvvvvvvvvo.',
    'ovvvvvvvvvvvvvo.',
    '.ovvvvvvvvvoovo.',
    '..oovvvvvoo.oo..',
    '....ooooo.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },
  trophy: { g: [
    '................',
    '.oooooooooooooo.',
    '.ogGGGGGGGGGggo.',
    '.oogGGGGGGGgoo..',
    'oo.ogyGGGGggo.oo',
    'ogo.ogGGGGgo.ogo',
    'ogo.ogGGGGgo.ogo',
    'ooo.ogGGGggo.ooo',
    '.....ogGggo.....',
    '......oggo......',
    '......oggo......',
    '.....ooggoo.....',
    '....oggggggo....',
    '...oggggggggo...',
    '...oooooooooo...',
    '................',
  ] },
  rod: { g: [
    '..............o.',
    '.............oo.',
    '...........ooNo.',
    '..........oNNoo.',
    '.........oNNo.o.',
    '........oNNo..o.',
    '.......onNo...o.',
    '......onno....o.',
    '.....onno.....o.',
    '....onno......o.',
    '...odno.......o.',
    '..odno......ooo.',
    '.oddo......orRo.',
    '.odo.......oRWo.',
    '.oo.........oo..',
    '................',
  ] },
  potion: { g: [
    '................',
    '......oooo......',
    '......osso......',
    '......owwo......',
    '......owwo......',
    '.....oowwoo.....',
    '....owwwwwwo....',
    '...owwwwwwwwo...',
    '..owwoppppwwwo..',
    '..owpPPpppppwo..',
    '..opPPPpppppo...',
    '..opPPpppppppo..',
    '..oppppppppppo..',
    '...oppppppppo...',
    '....oooooooo....',
    '................',
  ] },
  map: { g: [
    '................',
    '................',
    '..oo...ooo..oo..',
    '.oawooowawooawo.',
    '.oaawwawwawwaao.',
    '.oaawaaawaawaao.',
    '.oawwarraawwaao.',
    '.oawaarraaawaao.',
    '.oawaaaaaaawaao.',
    '.oawaaeeaawwaao.',
    '.oawaaeeaaawaao.',
    '.oaawaaaawaaawo.',
    '.oaawwaawwaawao.',
    '.oawooowawooawo.',
    '..oo...ooo..oo..',
    '................',
  ] },
  island: { g: [
    '................',
    '...oo.....oo....',
    '..oEEoo.ooEEo...',
    '.oEEEEEoEEEEEo..',
    '.oEeoeEEEeoeEEo.',
    '..ooooeEeooooo..',
    '......oeeo......',
    '......oeeo......',
    '.....oeeo.......',
    '.....oeeo.......',
    '.....oneo.......',
    '....oAAnAoo.....',
    '..ooAAAAAAAoo...',
    '.oaAAAAAAAAAao..',
    '.ooaaaaaaaaaoo..',
    '................',
  ] },
  settings: { g: [
    '................',
    '......oooo......',
    '..oo..oSSo..oo..',
    '.ossooossooosso.',
    '.osssssssssssso.',
    '..osssssssssso..',
    '..osssoooossso..',
    '..oSso....osso..',
    '..oSso....osso..',
    '..osssoooossso..',
    '..osssssssssso..',
    '.osssssssssssso.',
    '.ossooossooosso.',
    '..oo..osso..oo..',
    '......oooo......',
    '................',
  ] },
  lobby: { g: [
    '................',
    '................',
    '...ooo....ooo...',
    '..oNNNo..odddo..',
    '.oNyNNNoodydddo.',
    '.oNNNNNoodddddo.',
    '.oNNNNNoodddddo.',
    '..oNNNo..odddo..',
    '...ooo....ooo...',
    '..ooooo..ooooo..',
    '.orrrrroobbbbbo.',
    '.orRrrroobBbbbo.',
    '.orrrrroobbbbbo.',
    '.orrrrroobbbbbo.',
    '.ooooooooooooo..',
    '................',
  ] },
  close: { g: [
    '................',
    '................',
    '..oo........oo..',
    '.orro......orro.',
    '.oRrro....orrro.',
    '..orrro..orrro..',
    '...orrroorrro...',
    '....orrrrrro....',
    '.....orrrro.....',
    '....orrrrrro....',
    '...orrroorrro...',
    '..orrro..orrro..',
    '.orrro....orrro.',
    '.orro......orro.',
    '..oo........oo..',
    '................',
  ] },

  // --------------------------------------------------------- currency / HUD
  coin: { g: [
    '................',
    '.....oooooo.....',
    '...oogGGGGgoo...',
    '..ogyyGGGGGgo...',
    '..oyyGGGGGGGgo..',
    '.ogyGGGGGGGGggo.',
    '.ogyGGGGGGGGggo.',
    '.ogGGGGGGGGGggo.',
    '.ogGGGGGGGGGggo.',
    '.oggGGGGGGGgggo.',
    '..oggGGGGGgggo..',
    '..oggggggggggo..',
    '...ooggggggoo...',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  sun: { g: [
    '................',
    '.......oo.......',
    '.o.....oo.....o.',
    '..o..oooooo..o..',
    '...ooGGGGGGoo...',
    '...oGyyGGGGGo...',
    '..ooGyGGGGGGoo..',
    '.oooGGGGGGGGooo.',
    '.oooGGGGGGGGooo.',
    '..ooGGGGGGGGoo..',
    '...oGGGGGGGGo...',
    '...ooGGGGGGoo...',
    '..o..oooooo..o..',
    '.o.....oo.....o.',
    '.......oo.......',
    '................',
  ], p: { G: '#f4b93c' } },
  moon: { g: [
    '................',
    '.....ooooo......',
    '....oyyyyoo.....',
    '...oyyyoooo.....',
    '..oyyyo.........',
    '..oyyo..........',
    '.oyyyo.....o....',
    '.oyyyo....oyo...',
    '.oyyyo.....o....',
    '.oyyyo..........',
    '..oyyo..........',
    '..oyyyo.........',
    '...oyyyoooo.....',
    '....oyyyyoo.....',
    '.....ooooo......',
    '................',
  ], p: { y: '#f2d876' } },
  dusk: { g: [
    '................',
    '................',
    '................',
    '.......oo.......',
    '..o....oo....o..',
    '...o.oooooo.o...',
    '....ooGGGGoo....',
    '...ooGyGGGGoo...',
    '...oGyGGGGGGo...',
    '..ooGGGGGGGGoo..',
    'oooooooooooooooo',
    '.obbBbbbbbBbbbo.',
    '.obbbbBbbbbbbo..',
    '..oooooooooooo..',
    '................',
    '................',
  ], p: { G: '#f09c3a' } },
  bait: { g: [
    '................',
    '................',
    '................',
    '....ooooo.......',
    '...oiIIiioo.....',
    '..oiIooooiio....',
    '..oiio...oiio...',
    '..oiio....oiio..',
    '...oo......oiio.',
    '.....oo....oiio.',
    '....oiio..oiio..',
    '...oiiiooiiio...',
    '....oiiiiiio....',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  level: { g: [
    '................',
    '.......oo.......',
    '......oGGo......',
    '.....oGyGGo.....',
    '....oGyGGGGo....',
    '...oGGGGGGGGo...',
    '..oGGGGGGGGGGo..',
    '.oooooGGGGooooo.',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oGGGGo.....',
    '.....oooooo.....',
    '................',
    '................',
  ], p: { G: '#5cb85c', y: '#a8e6a0' } },
  xp: { g: [
    '................',
    '................',
    '.......oo.......',
    '......oGGo......',
    '......oGGo......',
    '.....oGyGGo.....',
    '..oooGyGGGooo...',
    '.oGGGGyGGGGGGo..',
    '..oooGGGGGooo...',
    '.....oGGGGo.....',
    '......oGGo......',
    '......oGGo......',
    '.......oo.......',
    '................',
    '................',
    '................',
  ] },

  // ---------------------------------------------------------------- fishing
  bobber: { g: [
    '................',
    '.......o........',
    '.......o........',
    '......ooo.......',
    '.....ooooo......',
    '....orrRrro.....',
    '...orrrRrrro....',
    '...orrrrrrro....',
    '...ooooooooo....',
    '...owwwwwwwo....',
    '...oWwwwwwwo....',
    '....owwwwwo.....',
    '.....ooooo......',
    '......ooo.......',
    '................',
    '................',
  ] },
  hook: { g: [
    '................',
    '......oo........',
    '.....oSso.......',
    '.....osso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '......oso.......',
    '..oo..oso.......',
    '.oSso.oso.......',
    '.osso.osso......',
    '..ossoosso......',
    '...ossssoo......',
    '....oooo........',
    '................',
  ] },
  reel: { g: [
    '................',
    '.....oooooo.....',
    '...ooddddddoo...',
    '..oddddddddddo..',
    '..oddooooooddo..',
    '.oddossssssoddo.',
    '.odosSssssssodo.',
    'oddosssoosssoddo',
    'oddosssoosssoddo',
    '.odossssssssodo.',
    '.oddosssssooddo.',
    '..oddoooooooddo.',
    '...ooddddddooGo.',
    '.....oooooo..o..',
    '................',
    '................',
  ], p: { d: '#7a3a20' } },
  gadget: { g: [
    '................',
    '................',
    '..oo......oo....',
    '.osSo....osSoo..',
    '.osso....osssso.',
    '.ossoo..oossso..',
    '.osssoooossso...',
    '..osssssssso....',
    '...oossssoo.....',
    '.....osssso.....',
    '......ossso.....',
    '.......ossso....',
    '........ossso...',
    '.........osso...',
    '..........oo....',
    '................',
  ] },
  sonar: { g: [
    '................',
    '................',
    '..ooo...........',
    '.oTTto...ooo....',
    '.oTto...ottto...',
    '.otto..otto.....',
    '.otto..otto..oo.',
    '.otto..otto.oto.',
    '.otto..otto.oto.',
    '.otto..otto..oo.',
    '.otto..otto.....',
    '.oTto...ottto...',
    '.oTTto...ooo....',
    '..ooo...........',
    '................',
    '................',
  ] },
  scope: { g: [
    '................',
    '................',
    '.........oooo...',
    '........okkkko..',
    '.......okLLsko..',
    '......okLskkko..',
    '.....osksskko...',
    '....ossso.oo....',
    '...ossso........',
    '...ossso........',
    '..onnso.........',
    '.onnno..........',
    '.onno...........',
    '..oo............',
    '................',
    '................',
  ] },

  magnet: { g: [
    '................',
    '................',
    '..oooo....oooo..',
    '.orrrro..orrrro.',
    '.oRrrro..orrRro.',
    '.orrrro..orrrro.',
    '.oooooo..oooooo.',
    '.oSSSSo..oSSSSo.',
    '.osssso..osssso.',
    '.ossssoooosssso.',
    '.osssssssssssso.',
    '..osssssssssso..',
    '...osssssssso...',
    '....oooooooo....',
    '................',
    '................',
  ] },
  autoreel: { g: [
    '.oooo...........',
    '..yyo...........',
    '..oy............',
    '.oyyo..oooo.....',
    '.oooo...yyo.....',
    '........oy......',
    '.......oyyo.....',
    '.......oooo.....',
    '....ooooo.......',
    '..oodddddoo.....',
    '.oddoooooddo....',
    '.odo.osso.odo...',
    '.odo.osso.odo...',
    '.oddoooooddo....',
    '..oodddddoo.....',
    '....ooooo.......',
  ], p: { d: '#7a3a20', y: '#f2d876' } },
  tension: { g: [
    '................',
    '......oooo......',
    '.....orrrro.....',
    '.....orRrro.....',
    '.....orRrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '.....orrrro.....',
    '......orro......',
    '......orro......',
    '.......oo.......',
    '......oooo......',
    '.....orrrro.....',
    '.....orrrro.....',
    '......oooo......',
    '................',
  ] },
  fish: { g: [
    '................',
    '................',
    '................',
    '.....ooooo......',
    '...oobBBbboo.oo.',
    '..obBBbbbbbooBo.',
    '.obBoWbbbbbboBBo',
    '.oboooObbbbbbBo.',
    '.obbbbbbbbbooBo.',
    '..obbbbbbbo.oBo.',
    '...oobbboo...oo.',
    '.....ooooo......',
    '................',
    '................',
    '................',
    '................',
  ] },
  fish_rare: { g: [
    '.......o........',
    '......oyo..o....',
    '.......o........',
    '.....ooooo......',
    '...ooGGGGgoo.oo.',
    '..oGGGggggggooGo',
    '.oGGoWgggggggGGo',
    '.ogoooOgggggggo.',
    '.oggggggggggooGo',
    '..ogggggggo..oGo',
    '...oogggoo....oo',
    '.....ooooo......',
    '..o.............',
    '.oyo............',
    '..o.............',
    '................',
  ] },
  whale: { g: [
    '................',
    '....o.o.........',
    '....ooo.........',
    '.....o..........',
    '....ooooooo.....',
    '..oobbbbbbboo...',
    '.obbbbbbbbbbboo.',
    'obbWobbbbbbbbobo',
    'obboobbbbbbbobbo',
    'obbbbbbbbbboobbo',
    '.oLLLbbbbbbbobo.',
    '..oLLLLbbbboo.o.',
    '...ooooooooo....',
    '................',
    '................',
    '................',
  ], p: { b: '#3a6ea8', L: '#bcd8ec' } },
  junk: { g: [
    '................',
    '................',
    '....oooo........',
    '...odddNo.......',
    '...oddddo.......',
    '...ododdo.......',
    '...odddNo.......',
    '...oddddo.......',
    '...oddddo.......',
    '...oddddoooo....',
    '...odddddNNNoo..',
    '...oddddddddNNo.',
    '..oododdddddddo.',
    '..oo.ooooooooo..',
    '................',
    '................',
  ], p: { d: '#6a4a2a', N: '#8a6a3a' } },
  treasure: { g: [
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..oNyNNNNNNNNo..',
    '..oNNNNNNNNNNo..',
    '.oooooooooooooo.',
    '.onnnnoggonnnno.',
    '.onnnnoGgonnnno.',
    '.onnnnoooonnnno.',
    '.onnnnnnnnnnnno.',
    '.onnnnnnnnnnnno.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ] },
  record: { g: [
    '................',
    '...ooooooooo....',
    '...obbo.orro....',
    '...obbo.orro....',
    '...obbo.orro....',
    '...obboorro.....',
    '....obboro......',
    '....ooooo.......',
    '...ooGGGoo......',
    '..oGGyGGGGo.....',
    '..oGyGooGGo.....',
    '..oGGoGGoGo.....',
    '..oGGoooGGo.....',
    '...oGGGGGo......',
    '....ooooo.......',
    '................',
  ] },

  // ---------------------------------------------------------- world/actions
  bank: { g: [
    '................',
    '................',
    '...oooooooooo...',
    '..odyddddddddo..',
    '..oddddddddddo..',
    '..ogGgggggggGo..',
    '.oooooooooooooo.',
    '.odddoggggodddo.',
    '.odddogGggodddo.',
    '.odddoggggodddo.',
    '.odddooooodddo..',
    '.odddddddddddo..',
    '.ogGgggggggggGo.',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  shop: { g: [
    '.oooooooooooooo.',
    '.owrwrwrwrwrwwo.',
    '.owrwrwrwrwrwwo.',
    '.oooooooooooooo.',
    '....o......o....',
    '....o......o....',
    '..oooooooooooo..',
    '.oNNNNNNNNNNNNo.',
    '.oNyNNNNNNNNNNo.',
    '.oNodoNNNNodoNo.',
    '.oNodoNNNNodoNo.',
    '.oNNNNNNNNNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  ferry: { g: [
    '................',
    '................',
    '.......oo.......',
    '......owwo......',
    '......owwoo.....',
    '......owwwwo....',
    '......owwwwwo...',
    '......oooooo....',
    '..o....odd..o...',
    '..oo...odd.oo...',
    '.oonoooooooooo..',
    '.onnnnnnnnnnno..',
    '..onnnnnnnnno...',
    '...ooooooooo....',
    '....bbBbbBbb....',
    '................',
  ] },
  portal: { g: [
    '................',
    '.....oooooo.....',
    '...ootTTTtoo....',
    '..otTToootTto...',
    '..oTto....otto..',
    '.otTo......otto.',
    '.oTto......otto.',
    '.oTto......otto.',
    '.otto......otto.',
    '.otto......otTo.',
    '..otto....otto..',
    '..ottToootTto...',
    '...ootTTTtoo....',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  talk: { g: [
    '................',
    '................',
    '..oooooooooooo..',
    '.owwwwwwwwwwwwo.',
    '.oWwwwwwwwwwwwo.',
    '.owwooWwooWwowo.',
    '.owwoowwoowwowo.',
    '.owwwwwwwwwwwwo.',
    '.owwwwwwwwwwwwo.',
    '..oooowwwooooo..',
    '.....owwo.......',
    '....owwo........',
    '...owwo.........',
    '...ooo..........',
    '................',
    '................',
  ] },
  examine: { g: [
    '................',
    '....ooooo.......',
    '...oosssoo......',
    '..oso...oso.....',
    '.oso.....oso....',
    '.oso..W..oso....',
    '.oso.....oso....',
    '.oso.....oso....',
    '..oso...oso.....',
    '...oosssoo......',
    '....ooooooo.....',
    '.......onnno....',
    '........onnno...',
    '.........onnno..',
    '..........ooo...',
    '................',
  ], p: { s: '#7ab8d8', W: '#e8f4fa' } },
  walk: { g: [
    '................',
    '.........ooo....',
    '........oNNNo...',
    '........oNNNo...',
    '........oNNNo...',
    '.........ooo....',
    '........oNNo....',
    '.........oo.....',
    '..ooo...........',
    '.oNNNo..........',
    '.oNNNo..........',
    '.oNNNo..........',
    '..ooo...........',
    '.oNNo...........',
    '..oo............',
    '................',
  ] },
  wave: { g: [
    '................',
    '.....o.o.o......',
    '....oNoNoNoo....',
    '....oNNNNNNNoo..',
    '.o..oNNNNNNNNNo.',
    '.oNooNNNNNNNNNo.',
    '..oNoNNNNNNNNNo.',
    '..oNNNNNNNNNNNo.',
    '...oNNyNNNNNNo..',
    '...oNNNNNNNNNo..',
    '....oNNNNNNNo...',
    '....oNNNNNNNo...',
    '.....ooooooo....',
    '................',
    '................',
    '................',
  ] },
  key: { g: [
    '................',
    '................',
    '...oooo.........',
    '..ogGGgo........',
    '.ogGo.ogo.......',
    '.oGo...ogo......',
    '.ogo..ogo.......',
    '..ogggo.ogo.....',
    '...oo....ogo....',
    '..........ogo...',
    '...........ogoo.',
    '..........ogGgo.',
    '.........ogo.go.',
    '..........oggo..',
    '...........oo...',
    '................',
  ] },
  sign: { g: [
    '................',
    '................',
    '..oooooooooooo..',
    '.oNyNNNNNNNNNNo.',
    '.oNNNddNddNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '.oNNdNddNdNNNNo.',
    '.oNNNNNNNNNNNNo.',
    '..oooooooooooo..',
    '......oddo......',
    '......oddo......',
    '......oddo......',
    '......oddo......',
    '.....ooddoo.....',
    '................',
    '................',
  ] },

  // -------------------------------------------------------- island/brewing
  farm: { g: [
    '................',
    '................',
    '................',
    '...oo....oo.....',
    '..oEEo..oEEoo...',
    '..oEEEooEEEEo...',
    '...ooEeoEEoo....',
    '.....oeeoo......',
    '......oeo.......',
    '......oeo.......',
    '..oooooeooooo...',
    '.odddddddddddo..',
    '.oddndddnddndo..',
    '..odddndddddo...',
    '...ooooooooo....',
    '................',
  ] },
  workshop: { g: [
    '................',
    '................',
    '...ooooooo......',
    '..osSSSssso.....',
    '.osSSsssssso....',
    '.ossooosssso....',
    '.osso.ooooo.....',
    '..oo..onno......',
    '......onno......',
    '.......onno.....',
    '.......onno.....',
    '........onno....',
    '........onno....',
    '.........onno...',
    '.........ooo....',
    '................',
  ] },
  brewery: { g: [
    '................',
    '....o..o..o.....',
    '..o..o..o..o....',
    '...oooooooo.....',
    '..oEeEEeEeEo....',
    '.oooooooooooo...',
    '.okkEeEEeEkko...',
    '..okkkkkkkko....',
    '.okkkkkkkkkko...',
    '.okWkkkkkkkko...',
    '.okkkkkkkkkko...',
    '..okkkkkkkko....',
    '...okkkkkko.....',
    '..oo.oooo.oo....',
    '..oo......oo....',
    '................',
  ], p: { k: '#2e2e38' } },
  shrine: { g: [
    '................',
    '.oo..........oo.',
    '..oooooooooooo..',
    '.orRRRRRRRRRRro.',
    '.orrrrrrrrrrrro.',
    '..oooooooooooo..',
    '....oro..oro....',
    '..oooroooorooo..',
    '..orrrrrrrrrro..',
    '...ooooo.oooo...',
    '....oro..oro....',
    '....oro..oro....',
    '....oro..oro....',
    '...orro..orro...',
    '...oooo..oooo...',
    '................',
  ] },
  seed: { g: [
    '................',
    '................',
    '................',
    '....oo..........',
    '...oNno...oo....',
    '..oNyno..oNno...',
    '..oNnno.oNyno...',
    '..onnno.oNnno...',
    '..onno..onnno...',
    '...oo...onno....',
    '.........oo.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },
  harvest: { g: [
    '................',
    '....o...o...o...',
    '...ogo.ogo.ogo..',
    '...oGgooGgooGgo.',
    '...ogGo.gGo.gGo.',
    '....ogo.ogo.ogo.',
    '....ogooogoogo..',
    '.....ogo.go.go..',
    '......ogogogo...',
    '.......ooooo....',
    '......odggdo....',
    '.......oggo.....',
    '.......oggo.....',
    '......oggggo....',
    '.......oooo.....',
    '................',
  ] },

  // ---------------------------------------------------- titles/achievements
  title: { g: [
    '................',
    '.....oooooo.....',
    '....orrRRrro....',
    '...orrRyyRrro...',
    '..orrRyGGyRrro..',
    '..orRyGGGGyRro..',
    '..orRyGGGGyRro..',
    '..orrRyGGyRrro..',
    '...orrRyyRrro...',
    '....orrRRrro....',
    '.....oorroo.....',
    '....oro..oro....',
    '...orro..orro...',
    '...oro....oro...',
    '....o......o....',
    '................',
  ] },
  secret: { g: [
    '................',
    '.oooooooooooooo.',
    '.oNNNNNNNNNNNNo.',
    '.oNyNooooooNNNo.',
    '.oNyoddddddoNNo.',
    '.oNyoddooddoNNo.',
    '.oNNoooo.oddoNo.',
    '.oNNNNN.oddoNNo.',
    '.oNNNNNoddoNNNo.',
    '.oNNNNNoddoNNNo.',
    '.oNNNNNooooNNNo.',
    '.oNNNNNoddoNNNo.',
    '.oNNNNNooooNNNo.',
    '.oNNNNNNNNNNNNo.',
    '.oooooooooooooo.',
    '................',
  ] },
  claim: { g: [
    '................',
    '.......oo.......',
    '......oyGo......',
    '......oGGo......',
    '.....oGGGGo.....',
    '.oo.oGGGGGGo.oo.',
    'oyGooGGGGGGooGGo',
    'oGGGGGGGGGGGGGGo',
    '.ooGGGGGGGGGGoo.',
    '...oGGGGGGGGo...',
    '....oGGGGGGo....',
    '....oGGooGGo....',
    '...oGGo..oGGo...',
    '...oGo....oGo...',
    '....o......o....',
    '................',
  ] },

  // ------------------------------------------------------------ chat/status
  muted: { g: [
    '................',
    '.o..............',
    '..ooooooooooo...',
    '.owwoowwwwwwwo..',
    '.owwwoowwwwwwo..',
    '.owwwwoowwwwwo..',
    '.owwwwwoowwwwo..',
    '.owwwwwwoowwwo..',
    '.owwwwwwwoowwo..',
    '..ooowwwwwoooo..',
    '....owwo..oo....',
    '...owwo.....o...',
    '..owwo..........',
    '..ooo...........',
    '................',
    '................',
  ] },
  crown: { g: [
    '................',
    '................',
    '................',
    '..oo....o....oo.',
    '.ogGo..ogo..oGgo',
    '.ogGo.ogGgo.oGgo',
    '.ogGooogGgoooGgo',
    '.ogGgggGGGgggGgo',
    '.ogyGGGGGGGGGGgo',
    '.ogyGgggggggggo.',
    '.oggo.......ogo.',
    '.oggggggggggggo.',
    '.oGGGGGGGGGGGGo.',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  kick: { g: [
    '................',
    '................',
    '....oooo........',
    '...odddNo.......',
    '...oddddo.......',
    '...odddNo..o....',
    '...oddddo.oWo...',
    '...oddddo..o....',
    '...oddddoooo.o..',
    '...odddddNNNooWo',
    '...oddddddddNNo.',
    '..oododdddddddo.',
    '..oo.ooooooooo..',
    '................',
    '................',
    '................',
  ], p: { d: '#6a4a2a', N: '#8a6a3a' } },
  ban: { g: [
    '................',
    '.....oooooo.....',
    '...oorrrrrroo...',
    '..orrRRrrrrrro..',
    '..orRRoooorrro..',
    '.orRRo...orrrro.',
    '.orRo.....orrro.',
    '.orro......orro.',
    '.orro.......oro.',
    '.orrro......oro.',
    '..orrro....oro..',
    '..orrrroooorro..',
    '...oorrrrrroo...',
    '.....oooooo.....',
    '................',
    '................',
  ] },
  system: { g: [
    '................',
    '................',
    '...ooooooooo....',
    '..owwwwwwwwoo...',
    '..owwwwwwwowwo..',
    '..owwwwwwwoooo..',
    '..owsswsswwwwo..',
    '..owwwwwwwwwwo..',
    '..owswsswswwwo..',
    '..owwwwwwwwwwo..',
    '..owsswswswwwo..',
    '..owwwwwwwwwwo..',
    '..oowwwwwwwwo...',
    '....oooooooo....',
    '................',
    '................',
  ] },
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export const ICON_NAMES = Object.freeze(Object.keys(GRIDS));

const _cache = new Map();

/** Render one 16x16 icon to a canvas and return a cached PNG data URL. */
export function iconDataUrl(name) {
  const hit = _cache.get(name);
  if (hit) return hit;
  const def = GRIDS[name] || GRIDS.secret;
  const canvas = document.createElement('canvas');
  canvas.width = 16;
  canvas.height = 16;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  const pal = def.p ? Object.assign({}, BASE_PALETTE, def.p) : BASE_PALETTE;
  const rows = def.g;
  for (let y = 0; y < 16; y++) {
    const row = rows[y] || '';
    let x = 0;
    while (x < 16) {
      const color = pal[row[x]];
      if (!color) { x++; continue; }
      let x2 = x + 1;
      while (x2 < 16 && row[x2] === row[x]) x2++;
      ctx.fillStyle = color;
      ctx.fillRect(x, y, x2 - x, 1);
      x = x2;
    }
  }
  const url = canvas.toDataURL('image/png');
  _cache.set(name, url);
  return url;
}

/** Create an <img> element for the named icon. */
export function icon(name, size = 16) {
  const el = document.createElement('img');
  el.width = size;
  el.height = size;
  el.style.imageRendering = 'pixelated';
  el.className = 'pxi';
  el.src = iconDataUrl(name);
  el.alt = name;
  return el;
}

/** HTML string form, for innerHTML-based call sites. */
export function iconHtml(name, size = 16) {
  return '<img class="pxi" src="' + iconDataUrl(name) +
    '" width="' + size + '" height="' + size +
    '" alt="' + name + '" style="image-rendering:pixelated">';
}
